# nixpacks.toml
[phases.setup]
nixPkgs = [
  "chromium",
  "nss",
  "nspr",
  "at-spi2-atk",
  "cups",
  "libdrm",
  "libxcomposite",
  "libxdamage",
  "libxrandr",
  "mesa",
  "alsa-lib",
  "pango",
  "cairo",
  "xorg.libxkbcommon",
  "xorg.libX11",
  "xorg.libXcursor",
  "xorg.libXext",
  "xorg.libXfixes",
  "xorg.libXi",
  "xorg.libXrender",
  "xorg.libXtst",
  "xorg.libXScrnSaver",
  "gtk3",
  "expat",
  "libxcb"
]

[phases.build]
cmds = ["npm ci"]

[phases.build.env]
PUPPETEER_SKIP_DOWNLOAD = "true"

[start]
cmd = "node server.js"

[start.env]
PUPPETEER_EXECUTABLE_PATH = "/run/current-system/sw/bin/chromium"
